// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RWD.Infrastructure.Diagram.Infrastructure.Persistence;

#nullable disable

namespace RWD.Infrastructure.Diagram.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622170336_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.App", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HardwareId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Https")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VirtualMachineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HardwareId");

                    b.HasIndex("VirtualMachineId");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.Hardware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Os")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RamGb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hardwares");
                });

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.MapLayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Locked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("MapLayouts");
                });

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.Network", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gateway")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subnet")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Networks");
                });

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.NetworkMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpOnNetwork")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MemberType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("NetworkId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NetworkId");

                    b.ToTable("NetworkMembers");
                });

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.NetworkShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShareType")
                        .HasColumnType("TEXT");

                    b.Property<int>("StorageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StorageId");

                    b.ToTable("NetworkShares");
                });

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.Relationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HardwareId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RaidType")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("UsableSpaceTb")
                        .HasColumnType("REAL");

                    b.Property<int?>("VirtualMachineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HardwareId");

                    b.HasIndex("VirtualMachineId");

                    b.ToTable("StoragePools");
                });

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.VirtualMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CpuCores")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiskGb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HardwareId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hostname")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Os")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RamGb")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HardwareId");

                    b.ToTable("VirtualMachines");
                });

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.App", b =>
                {
                    b.HasOne("RWD.Infrastructure.Diagram.Core.Domain.Entities.Hardware", "Hardware")
                        .WithMany("Apps")
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RWD.Infrastructure.Diagram.Core.Domain.Entities.VirtualMachine", "VirtualMachine")
                        .WithMany("Apps")
                        .HasForeignKey("VirtualMachineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Hardware");

                    b.Navigation("VirtualMachine");
                });

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.Document", b =>
                {
                    b.HasOne("RWD.Infrastructure.Diagram.Core.Domain.Entities.Document", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.NetworkMember", b =>
                {
                    b.HasOne("RWD.Infrastructure.Diagram.Core.Domain.Entities.Network", "Network")
                        .WithMany("Members")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Network");
                });

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.NetworkShare", b =>
                {
                    b.HasOne("RWD.Infrastructure.Diagram.Core.Domain.Entities.Storage", "Storage")
                        .WithMany("Shares")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.Storage", b =>
                {
                    b.HasOne("RWD.Infrastructure.Diagram.Core.Domain.Entities.Hardware", "Hardware")
                        .WithMany("StoragePools")
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RWD.Infrastructure.Diagram.Core.Domain.Entities.VirtualMachine", "VirtualMachine")
                        .WithMany("StoragePools")
                        .HasForeignKey("VirtualMachineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Hardware");

                    b.Navigation("VirtualMachine");
                });

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.VirtualMachine", b =>
                {
                    b.HasOne("RWD.Infrastructure.Diagram.Core.Domain.Entities.Hardware", "Hardware")
                        .WithMany("VirtualMachines")
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hardware");
                });

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.Document", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.Hardware", b =>
                {
                    b.Navigation("Apps");

                    b.Navigation("StoragePools");

                    b.Navigation("VirtualMachines");
                });

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.Network", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.Storage", b =>
                {
                    b.Navigation("Shares");
                });

            modelBuilder.Entity("RWD.Infrastructure.Diagram.Core.Domain.Entities.VirtualMachine", b =>
                {
                    b.Navigation("Apps");

                    b.Navigation("StoragePools");
                });
#pragma warning restore 612, 618
        }
    }
}
